another yaml test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -63,7 +63,13 @@ jobs:
           
           if [ "$TEST_ERRORS" != "Keine Fehler gefunden" ] || [ "$LINT_ERRORS" != "Keine Fehler gefunden" ]; then
             curl -X POST -H 'Content-Type: application/json' \
-            --data "{\"type\": \"stream\", \"to\": \"${{ secrets.ZULIP_CHANNEL }}\", \"content\": \"$MESSAGE\"}" \
-            -u "${{ secrets.ZULIP_EMAIL }}:${{ secrets.ZULIP_API_KEY }}" \
-            https://ihkprojekt.zulipchat.com/api/v1/messages
+            --data "{\"type\": \"stream\", \"to\": \"${{ secrets.ZULIP_CHANNEL }}\", \"topic\": \"CI Status\", \"content\": \"$MESSAGE\"}" \
+            -u "${{ secrets.ZULIP_BOT_EMAIL }}:${{ secrets.ZULIP_API_KEY }}" \
+            https://ihkprojekt.zulipchat.com/api/v1/send_message || echo "Failed to send message"
+          else
+            MESSAGE="Tests erfolgreich oder keine Fehler gefunden."
+            curl -X POST -H 'Content-Type: application/json' \
+            --data "{\"type\": \"stream\", \"to\": \"${{ secrets.ZULIP_CHANNEL }}\", \"topic\": \"CI Status\", \"content\": \"$MESSAGE\"}" \
+            -u "${{ secrets.ZULIP_BOT_EMAIL }}:${{ secrets.ZULIP_API_KEY }}" \
+            https://ihkprojekt.zulipchat.com/api/v1/send_message || echo "Failed to send message"
           fi
